/**
 * Códigos de error estables del API.
 *
 * Decisión PR0: cada `BusinessError` lleva un código de este enum además
 * del mensaje en español. El FE puede reaccionar al código sin parsear el mensaje.
 *
 * Reglas para sumar códigos:
 * - Convención: SCREAMING_SNAKE_CASE.
 * - Prefijo opcional por feature (`PAYMENT_*`, `REGISTRATION_*`).
 * - Una vez agregado y publicado, NO renombrar — el FE puede depender de él.
 *
 * Cada feature de Olas 1-3 puede sumar sus propios códigos en su PR.
 */
export enum ErrorCode {
  // Generic
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Auth / users
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  PROFILE_DNI_REQUIRED = 'PROFILE_DNI_REQUIRED', // RN-034
  PROFILE_DNI_NOT_VERIFIED = 'PROFILE_DNI_NOT_VERIFIED', // RN-034, RN-035

  // Teams
  TEAM_PLAYER_ALREADY_IN_OTHER_TEAM = 'TEAM_PLAYER_ALREADY_IN_OTHER_TEAM', // RN-002
  TEAM_NOT_CATEGORIZED = 'TEAM_NOT_CATEGORIZED', // RN-039
  TEAM_NOT_ELIGIBLE_FOR_CATEGORY = 'TEAM_NOT_ELIGIBLE_FOR_CATEGORY', // RN-044
  TEAM_ROSTER_BELOW_MIN = 'TEAM_ROSTER_BELOW_MIN', // RN-009
  TEAM_ROSTER_ABOVE_MAX = 'TEAM_ROSTER_ABOVE_MAX',

  // Registrations
  REGISTRATION_DUPLICATE = 'REGISTRATION_DUPLICATE', // RN-040 — equipo ya inscripto en torneo
  REGISTRATION_TOURNAMENT_CLOSED = 'REGISTRATION_TOURNAMENT_CLOSED',
  REGISTRATION_INSURANCE_PENDING = 'REGISTRATION_INSURANCE_PENDING', // RN-016
  REGISTRATION_PLAYER_CONFLICT = 'REGISTRATION_PLAYER_CONFLICT', // RN-007 / RN-038 / RN-041
  REGISTRATION_LATE_ROSTER_FEE_REQUIRED = 'REGISTRATION_LATE_ROSTER_FEE_REQUIRED', // RN-042

  // Tournaments / categories
  TOURNAMENT_INVALID_MODALITY = 'TOURNAMENT_INVALID_MODALITY',
  TOURNAMENT_INVALID_STATUS_TRANSITION = 'TOURNAMENT_INVALID_STATUS_TRANSITION',
  TOURNAMENT_NOT_FOUND = 'TOURNAMENT_NOT_FOUND',
  PRICING_PERIOD_OVERLAP = 'PRICING_PERIOD_OVERLAP', // RN-048
  PRICING_PERIOD_NOT_FOUND = 'PRICING_PERIOD_NOT_FOUND',
  PRICING_NOT_CONFIGURED = 'PRICING_NOT_CONFIGURED', // W2.3 — computeRegistrationFee sin pricing aplicable
  PRICING_INVALID_PAYMENT_METHOD = 'PRICING_INVALID_PAYMENT_METHOD', // W2.3 — método de pago inválido
  DISCOUNT_NOT_FOUND = 'DISCOUNT_NOT_FOUND', // W2.3 — descuentos manuales (RN-020)
  DISCOUNT_AMOUNT_INVALID = 'DISCOUNT_AMOUNT_INVALID', // W2.3 — monto debe ser > 0
  DISCOUNT_ALREADY_CANCELLED = 'DISCOUNT_ALREADY_CANCELLED', // W2.3 — descuento ya cancelado
  FRANCHISE_DISCOUNT_NOT_IMPLEMENTED = 'FRANCHISE_DISCOUNT_NOT_IMPLEMENTED', // DP-011 — pendiente
  CATEGORY_PLAYOFF_FORMAT_LOCKED = 'CATEGORY_PLAYOFF_FORMAT_LOCKED', // RN-047 — ya empezaron playoffs
  CATEGORY_TOO_MANY_ZONES = 'CATEGORY_TOO_MANY_ZONES', // DP-003 — máx 2 zonas

  // Matches
  MATCH_INVALID_SCORE = 'MATCH_INVALID_SCORE',
  MATCH_STAFF_BELOW_MIN = 'MATCH_STAFF_BELOW_MIN', // RN-049
  MATCH_TEAM_HAS_OUTSTANDING_DEBT = 'MATCH_TEAM_HAS_OUTSTANDING_DEBT', // RN-053
  MATCH_PLAYERS_BELOW_MIN = 'MATCH_PLAYERS_BELOW_MIN',
  MATCH_INVALID_STATUS_TRANSITION = 'MATCH_INVALID_STATUS_TRANSITION', // W3.1
  MATCH_CANCEL_WINDOW_EXPIRED = 'MATCH_CANCEL_WINDOW_EXPIRED', // RN-032 — fuera del plazo de 72h
  MATCH_CANCEL_NOT_ALLOWED = 'MATCH_CANCEL_NOT_ALLOWED', // estado no permite cancelación
  MATCH_RIVAL_DECISION_NOT_PENDING = 'MATCH_RIVAL_DECISION_NOT_PENDING', // RN-032
  MATCH_NOT_SUSPENDED = 'MATCH_NOT_SUSPENDED', // resolve-suspended sobre no-suspendido
  MATCH_RESOLUTION_INVALID = 'MATCH_RESOLUTION_INVALID',

  // Playoffs
  PLAYOFF_PHASE_NOT_READY = 'PLAYOFF_PHASE_NOT_READY', // regular incompleta o substatus inválido
  PLAYOFF_ALREADY_GENERATED = 'PLAYOFF_ALREADY_GENERATED',
  PLAYOFF_INSUFFICIENT_TEAMS = 'PLAYOFF_INSUFFICIENT_TEAMS', // no hay clasificados suficientes
  PLAYOFF_OVERRIDE_LOCKED = 'PLAYOFF_OVERRIDE_LOCKED', // ya hay matches en curso/finalizados
  PLAYOFF_SERIES_NOT_TIE = 'PLAYOFF_SERIES_NOT_TIE', // tiebreaker sobre serie definida
  PLAYOFF_PROMOTION_NOT_READY = 'PLAYOFF_PROMOTION_NOT_READY', // RN-058 — torneo no terminado

  // Staff / AJC (W3.2)
  STAFF_NOT_FOUND = 'STAFF_NOT_FOUND',
  STAFF_NOT_AVAILABLE = 'STAFF_NOT_AVAILABLE', // RN-050 — sin disponibilidad horaria
  STAFF_HAS_CONFLICT = 'STAFF_HAS_CONFLICT', // overlapping match
  STAFF_TYPE_ROLE_MISMATCH = 'STAFF_TYPE_ROLE_MISMATCH',
  STAFF_ALREADY_ASSIGNED = 'STAFF_ALREADY_ASSIGNED',
  AJC_INVALID_SANCTION = 'AJC_INVALID_SANCTION', // RN-030 — la sanción no es DISCIPLINARY o no está activa
  AJC_INVALID_FECHAS = 'AJC_INVALID_FECHAS', // RN-030 — fechasToFree <= 0 o excede el remanente

  // Friendlies
  FRIENDLY_DEPOSIT_WINDOW_EXPIRED = 'FRIENDLY_DEPOSIT_WINDOW_EXPIRED', // RN-023
  FRIENDLY_INVALID_TRANSITION = 'FRIENDLY_INVALID_TRANSITION',

  // Debts / payments
  DEBT_ALREADY_PAID = 'DEBT_ALREADY_PAID',
  DEBT_AMOUNT_EXCEEDS_BALANCE = 'DEBT_AMOUNT_EXCEEDS_BALANCE',
  DEBT_INVALID_STATUS_TRANSITION = 'DEBT_INVALID_STATUS_TRANSITION',
  PAYMENT_PROOF_REQUIRED = 'PAYMENT_PROOF_REQUIRED', // RN-014
  PAYMENT_METHOD_INVALID = 'PAYMENT_METHOD_INVALID',

  // Storage
  MEDIA_ASSET_NOT_FOUND = 'MEDIA_ASSET_NOT_FOUND',
  MEDIA_UPLOAD_FAILED = 'MEDIA_UPLOAD_FAILED',

  // Sport rules
  SPORT_RULES_NOT_FOUND = 'SPORT_RULES_NOT_FOUND',
}
