/**
 * Códigos de error estables del API.
 *
 * Decisión PR0: cada `BusinessError` lleva un código de este enum además
 * del mensaje en español. El FE puede reaccionar al código sin parsear el mensaje.
 *
 * Reglas para sumar códigos:
 * - Convención: SCREAMING_SNAKE_CASE.
 * - Prefijo opcional por feature (`PAYMENT_*`, `REGISTRATION_*`).
 * - Una vez agregado y publicado, NO renombrar — el FE puede depender de él.
 *
 * Cada feature de Olas 1-3 puede sumar sus propios códigos en su PR.
 */
export enum ErrorCode {
  // Generic
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Auth / users
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  PROFILE_DNI_REQUIRED = 'PROFILE_DNI_REQUIRED', // RN-034
  PROFILE_DNI_NOT_VERIFIED = 'PROFILE_DNI_NOT_VERIFIED', // RN-034, RN-035

  // Teams
  TEAM_PLAYER_ALREADY_IN_OTHER_TEAM = 'TEAM_PLAYER_ALREADY_IN_OTHER_TEAM', // RN-002
  TEAM_NOT_CATEGORIZED = 'TEAM_NOT_CATEGORIZED', // RN-039
  TEAM_NOT_ELIGIBLE_FOR_CATEGORY = 'TEAM_NOT_ELIGIBLE_FOR_CATEGORY', // RN-044
  TEAM_ROSTER_BELOW_MIN = 'TEAM_ROSTER_BELOW_MIN', // RN-009
  TEAM_ROSTER_ABOVE_MAX = 'TEAM_ROSTER_ABOVE_MAX',

  // Registrations
  REGISTRATION_DUPLICATE = 'REGISTRATION_DUPLICATE', // RN-040 — equipo ya inscripto en torneo
  REGISTRATION_TOURNAMENT_CLOSED = 'REGISTRATION_TOURNAMENT_CLOSED',
  REGISTRATION_INSURANCE_PENDING = 'REGISTRATION_INSURANCE_PENDING', // RN-016
  REGISTRATION_PLAYER_CONFLICT = 'REGISTRATION_PLAYER_CONFLICT', // RN-007 / RN-038 / RN-041
  REGISTRATION_LATE_ROSTER_FEE_REQUIRED = 'REGISTRATION_LATE_ROSTER_FEE_REQUIRED', // RN-042

  // Tournaments / categories
  TOURNAMENT_INVALID_MODALITY = 'TOURNAMENT_INVALID_MODALITY',
  TOURNAMENT_INVALID_STATUS_TRANSITION = 'TOURNAMENT_INVALID_STATUS_TRANSITION',
  CATEGORY_PLAYOFF_FORMAT_LOCKED = 'CATEGORY_PLAYOFF_FORMAT_LOCKED', // RN-047 — ya empezaron playoffs
  CATEGORY_TOO_MANY_ZONES = 'CATEGORY_TOO_MANY_ZONES', // DP-003 — máx 2 zonas

  // Matches
  MATCH_INVALID_SCORE = 'MATCH_INVALID_SCORE',
  MATCH_STAFF_BELOW_MIN = 'MATCH_STAFF_BELOW_MIN', // RN-049
  MATCH_TEAM_HAS_OUTSTANDING_DEBT = 'MATCH_TEAM_HAS_OUTSTANDING_DEBT', // RN-053
  MATCH_PLAYERS_BELOW_MIN = 'MATCH_PLAYERS_BELOW_MIN',

  // Friendlies
  FRIENDLY_DEPOSIT_WINDOW_EXPIRED = 'FRIENDLY_DEPOSIT_WINDOW_EXPIRED', // RN-023
  FRIENDLY_INVALID_TRANSITION = 'FRIENDLY_INVALID_TRANSITION',

  // Debts / payments
  DEBT_ALREADY_PAID = 'DEBT_ALREADY_PAID',
  DEBT_AMOUNT_EXCEEDS_BALANCE = 'DEBT_AMOUNT_EXCEEDS_BALANCE',
  DEBT_INVALID_STATUS_TRANSITION = 'DEBT_INVALID_STATUS_TRANSITION',
  PAYMENT_PROOF_REQUIRED = 'PAYMENT_PROOF_REQUIRED', // RN-014
  PAYMENT_METHOD_INVALID = 'PAYMENT_METHOD_INVALID',

  // Storage
  MEDIA_ASSET_NOT_FOUND = 'MEDIA_ASSET_NOT_FOUND',
  MEDIA_UPLOAD_FAILED = 'MEDIA_UPLOAD_FAILED',

  // Sport rules
  SPORT_RULES_NOT_FOUND = 'SPORT_RULES_NOT_FOUND',
}
