/**
 * Códigos de error del API. Mantener sincronizado con
 * `apps/api/src/common/errors/error-codes.ts`.
 *
 * El FE matchea por código (no por mensaje) para reaccionar a errores
 * conocidos de forma estable.
 */
export enum ErrorCode {
  // Generic
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Auth / users
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  PROFILE_DNI_REQUIRED = 'PROFILE_DNI_REQUIRED',
  PROFILE_DNI_NOT_VERIFIED = 'PROFILE_DNI_NOT_VERIFIED',

  // Teams
  TEAM_PLAYER_ALREADY_IN_OTHER_TEAM = 'TEAM_PLAYER_ALREADY_IN_OTHER_TEAM',
  TEAM_NOT_CATEGORIZED = 'TEAM_NOT_CATEGORIZED',
  TEAM_NOT_ELIGIBLE_FOR_CATEGORY = 'TEAM_NOT_ELIGIBLE_FOR_CATEGORY',
  TEAM_ROSTER_BELOW_MIN = 'TEAM_ROSTER_BELOW_MIN',
  TEAM_ROSTER_ABOVE_MAX = 'TEAM_ROSTER_ABOVE_MAX',

  // Registrations
  REGISTRATION_DUPLICATE = 'REGISTRATION_DUPLICATE',
  REGISTRATION_TOURNAMENT_CLOSED = 'REGISTRATION_TOURNAMENT_CLOSED',
  REGISTRATION_INSURANCE_PENDING = 'REGISTRATION_INSURANCE_PENDING',
  REGISTRATION_PLAYER_CONFLICT = 'REGISTRATION_PLAYER_CONFLICT',
  REGISTRATION_LATE_ROSTER_FEE_REQUIRED = 'REGISTRATION_LATE_ROSTER_FEE_REQUIRED',

  // Tournaments / categories
  TOURNAMENT_INVALID_MODALITY = 'TOURNAMENT_INVALID_MODALITY',
  TOURNAMENT_INVALID_STATUS_TRANSITION = 'TOURNAMENT_INVALID_STATUS_TRANSITION',
  TOURNAMENT_NOT_FOUND = 'TOURNAMENT_NOT_FOUND',
  PRICING_PERIOD_OVERLAP = 'PRICING_PERIOD_OVERLAP',
  PRICING_PERIOD_NOT_FOUND = 'PRICING_PERIOD_NOT_FOUND',
  PRICING_NOT_CONFIGURED = 'PRICING_NOT_CONFIGURED',
  PRICING_INVALID_PAYMENT_METHOD = 'PRICING_INVALID_PAYMENT_METHOD',
  DISCOUNT_NOT_FOUND = 'DISCOUNT_NOT_FOUND',
  DISCOUNT_AMOUNT_INVALID = 'DISCOUNT_AMOUNT_INVALID',
  DISCOUNT_ALREADY_CANCELLED = 'DISCOUNT_ALREADY_CANCELLED',
  FRANCHISE_DISCOUNT_NOT_IMPLEMENTED = 'FRANCHISE_DISCOUNT_NOT_IMPLEMENTED',
  CATEGORY_PLAYOFF_FORMAT_LOCKED = 'CATEGORY_PLAYOFF_FORMAT_LOCKED',
  CATEGORY_TOO_MANY_ZONES = 'CATEGORY_TOO_MANY_ZONES',

  // Matches
  MATCH_INVALID_SCORE = 'MATCH_INVALID_SCORE',
  MATCH_STAFF_BELOW_MIN = 'MATCH_STAFF_BELOW_MIN',
  MATCH_TEAM_HAS_OUTSTANDING_DEBT = 'MATCH_TEAM_HAS_OUTSTANDING_DEBT',
  MATCH_PLAYERS_BELOW_MIN = 'MATCH_PLAYERS_BELOW_MIN',

  // Friendlies
  FRIENDLY_DEPOSIT_WINDOW_EXPIRED = 'FRIENDLY_DEPOSIT_WINDOW_EXPIRED',
  FRIENDLY_INVALID_TRANSITION = 'FRIENDLY_INVALID_TRANSITION',

  // Debts / payments
  DEBT_ALREADY_PAID = 'DEBT_ALREADY_PAID',
  DEBT_AMOUNT_EXCEEDS_BALANCE = 'DEBT_AMOUNT_EXCEEDS_BALANCE',
  DEBT_INVALID_STATUS_TRANSITION = 'DEBT_INVALID_STATUS_TRANSITION',
  PAYMENT_PROOF_REQUIRED = 'PAYMENT_PROOF_REQUIRED',
  PAYMENT_METHOD_INVALID = 'PAYMENT_METHOD_INVALID',

  // Storage
  MEDIA_ASSET_NOT_FOUND = 'MEDIA_ASSET_NOT_FOUND',
  MEDIA_UPLOAD_FAILED = 'MEDIA_UPLOAD_FAILED',

  // Sport rules
  SPORT_RULES_NOT_FOUND = 'SPORT_RULES_NOT_FOUND',
}

/**
 * Forma del error que devuelve el API ante un `BusinessError`.
 * El FE puede typearlo y matchear por `code`.
 */
export interface ApiErrorResponse {
  statusCode: number;
  timestamp: string;
  path: string;
  method: string;
  code: ErrorCode;
  message: string;
  error: string;
  details?: Record<string, unknown>;
}
