export enum TournamentStatus {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  INSCRIPTION_OPEN = "INSCRIPTION_OPEN",
  INSCRIPTION_CLOSED = "INSCRIPTION_CLOSED",
  IN_PROGRESS = "IN_PROGRESS",
  PLAYING = "PLAYING",
  FINISHED = "FINISHED",
  ARCHIVED = "ARCHIVED",
}

export enum FixtureFormat {
  SINGLE_ROUND = "SINGLE_ROUND",
  DOUBLE_ROUND = "DOUBLE_ROUND",
}
